// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "navbar": {
    "articles": "Artiklar",
    "main_article_label": "Hushållskalkyl",
    "main_article_desc": "Hushållskalkylen hjälper dig att förstå din ekonomi bättre",
    "guides": "Guider",
    "budget_tools": "Budgetverktyg",
    "compound_interest": "Ränta-på-Ränta",
    "compound_interest_label": "Ränta-på-Ränta Kalkylator",
    "compound_interest_desc": "Se hur dina investeringar växer genom sammansatt avkastning"
  },
  "loan_parameters": {
    "title": "Låneparametrar",
    "add_loans": "Lägg till lån",
    "hide_loans": "Dölj lån",
    "loan_amount": "Lånebelopp (SEK)",
    "interest_rates": "Räntesatser (%)",
    "amortization_rates": "Amorteringssatser (%)",
    "title_aria": "Avsnitt för låneparametrar",
    "loan_amount_aria": "Lånebelopp i SEK",
    "interest_rates_aria": "Välj en eller flera räntesatser",
    "amortization_rates_aria": "Välj en eller flera amorteringssatser",
    "estimated_monthly_payment": "Beräknad månadskostnad",
    "monthly": "Månadskostnad",
    "total_interest": "Total ränta",
    "no_loan": "Jag har inga lån",
    "has_loan": "Jag har lån",
    "validation_rates_required": "Välj minst en räntesats och en amorteringssats när du anger ett lånebelopp",
    "validation_loan_amount_required": "Ange ett lånebelopp när du väljer räntor"
  },
  "dialog_hushallskalkyl": {
    "close": "Stäng",
    "title": "Hushållskalkyl & Hushållsbudget",
    "description": "Skapa din hushållsbudget och hushållskalkyl enkelt med Budgetkollen. Få full kontroll över din ekonomi och planera för framtiden.",
    "cta": "Läs mer"
  },
  "expense_categories": {
    "title": "Utgiftskategorier",
    "add_expenses": "Lägg till utgifter",
    "hide_expenses": "Dölj utgifter",
    "total_expenses": "Totala utgifter",
    "home": {
      "name": "Hem",
      "electricity-heating": "El och uppvärmning",
      "pets": "Husdjur",
      "streaming-internet-phone": "Streaming, internet och telefon",
      "house-cleaning": "Städning",
      "rent-monthly-fee": "Hyra och avgift",
      "interior-decoration": "Inredning och möbler",
      "mortgage": "Bolån",
      "home-improvements": "Renovering och förbättringar",
      "holiday-home": "Fritidshus",
      "water-garbage": "Vatten och sophämtning",
      "gardening": "Trädgård",
      "home-alarm": "Larm",
      "other-household": "Övriga hushållstjänster"
    },
    "car-transportation": {
      "name": "Bil och transport",
      "charging": "Laddning",
      "parking": "Parkering",
      "fuel": "Bränsle",
      "car-service": "Bilservice",
      "taxi": "Taxi",
      "public-transportation": "Kollektivtrafik",
      "car-cleaning": "Biltvätt",
      "car-loan-lease": "Billån och leasing",
      "motorcycle": "Motorcykel",
      "other-transportation": "Övriga transporter"
    },
    "leisure": {
      "name": "Fritid",
      "association-memberships": "Föreningsmedlemskap",
      "golfing": "Golf",
      "hunting": "Jakt",
      "hiking-outdoor": "Vandring och friluftsliv",
      "arts-crafts": "Konst och hantverk",
      "dancing": "Dans",
      "skiing-winter": "Skidåkning och vintersport",
      "horseback-riding": "Ridning",
      "biking": "Cykling",
      "photographing": "Fotografering",
      "music-instruments": "Musik och instrument",
      "parties-celebrations": "Fester och firanden",
      "charities": "Välgörenhet",
      "movies-events": "Bio, teater och evenemang",
      "lotteries-betting": "Lotterier och spel",
      "bars-nightclubs": "Barer, pubar och nattklubbar"
    },
    "shopping-services": {
      "name": "Shopping och tjänster",
      "flowers-decor": "Blommor och dekoration",
      "electronics": "Hemelektronik",
      "books-games": "Böcker och spel",
      "music-apps": "Musik och appar",
      "subscriptions-media": "Prenumerationer och media",
      "clothes-shoes": "Kläder och skor",
      "dry-clean-tailor": "Kemtvätt och skräddare",
      "jewelry-accessories": "Smycken och accessoarer",
      "tobacco": "Tobak",
      "alcohol": "Alkohol",
      "gifts": "Presenter",
      "shopping-other": "Shopping och tjänster, övrigt"
    },
    "loans-tax-fees": {
      "name": "Lån, skatt och avgifter",
      "late-fees": "Förseningsavgifter",
      "bank-fees": "Bank- och serviceavgifter",
      "private-loans": "Privatlån",
      "tax-payments": "Skattebetalningar",
      "other-loans-fees": "Övriga lån, skatter och avgifter"
    },
    "health-beauty": {
      "name": "Hälsa och skönhet",
      "pharmacy": "Apotek",
      "healthcare": "Sjukvård",
      "sports-exercise": "Sport och träning",
      "spa-massage": "Spa och massage",
      "beauty-products": "Skönhetsprodukter",
      "hairdresser": "Frisör",
      "optician": "Optiker",
      "other-health-beauty": "Övrig hälsa och skönhet"
    },
    "children": {
      "name": "Barn",
      "babysitting": "Barnpassning",
      "children-clothing": "Barnkläder",
      "children-toys": "Barnleksaker",
      "allowance": "Vecko- och månadspeng",
      "children-activities": "Barnaktiviteter",
      "childcare-products": "Barnomsorgsprodukter",
      "alimony": "Underhåll",
      "preschool-after-school": "Förskola och fritids",
      "children-other": "Barn, övrigt"
    },
    "uncategorized": {
      "name": "Okategoriserade utgifter",
      "cash-withdrawals": "Kontantuttag",
      "swish": "Swish",
      "uncategorized-transfers": "Okategoriserade överföringar",
      "uncategorized-other": "Okategoriserade utgifter, övrigt",
      "uncategorized-credit-card": "Okategoriserade kortköp"
    },
    "insurance": {
      "name": "Försäkring",
      "household-insurance": "Hemförsäkring",
      "car-insurance": "Bilförsäkring",
      "life-health-insurance": "Liv- och sjukförsäkring",
      "income-insurance": "A-kassa och/eller inkomstförsäkring",
      "accident-insurance": "Olycksfallsförsäkring",
      "insurance-other": "Övriga försäkringar"
    },
    "savings-investments": {
      "name": "Sparande och investeringar",
      "savings-buffer": "Buffertsparande",
      "pension-savings": "Pensionssparande",
      "securities-funds": "Värdepapper och fonder",
      "savings-children": "Barnsparande",
      "savings-other": "Sparande, övrigt"
    },
    "vacation-traveling": {
      "name": "Semester och resor",
      "vacation-transport": "Transport på semester",
      "hotels-accommodation": "Hotell och boende",
      "vacation-entertainment": "Nöjen på semester",
      "vacation-food": "Mat och levnadskostnader på semester",
      "vacation-other": "Semester och resor, övrigt"
    },
    "education": {
      "name": "Utbildning",
      "student-loan": "Studielån",
      "education-fees": "Utbildningsavgifter",
      "educational-equipment": "Utbildningsmaterial",
      "education-other": "Utbildning, övrigt"
    },
    "food": {
      "name": "Mat",
      "groceries": "Livsmedel",
      "fast-food": "Snabbmat",
      "candy-kiosks": "Godis, glass och kiosker",
      "restaurants-cafes": "Restauranger och caféer",
      "food-other": "Mat, övrigt"
    },
    "aria": {
      "title": "Utgiftskategorier sektion",
      "category": "Utgiftskategori: {{category}}",
      "subcategory_input": "Inmatning för {{subcategory}} i {{category}}"
    },
    "track_expenses": "Följ dina månatliga utgifter per kategori"
  },
  "expense_breakdown": {
    "title": "Utgiftsfördelning",
    "aria": {
      "title": "Utgiftsfördelning sektion"
    },
    "no_expenses": "Inga utgifter att visa",
    "total": "Totalt: {amount}",
    "legend_amount": "{amount}",
    "legend_percentage": "{percentage}%",
    "legend_label": "{name}: {amount} ({percentage}%)"
  },
  "results": {
    "title": "Beräkningsresultat",
    "aria": {
      "title": "Beräkningsresultat sektion"
    },
    "interest_rate": "Ränta",
    "amortization": "Amortering",
    "housing_cost": "Boendekostnad",
    "total_expenses": "Totala utgifter",
    "total_income": "Total inkomst",
    "remaining_savings": "Kvar att spara",
    "interest_rate_tooltip": "Räntesatsen som används för låneberäkningen.",
    "amortization_tooltip": "Amorteringssatsen som används för låneberäkningen.",
    "housing_cost_tooltip": "Summa av amorteringar, räntebetalningar, hyra/månadsavgift, el/värme, bolån och vatten/sopor.",
    "total_expenses_tooltip": "Alla månatliga utgifter, inklusive boende och övriga kategorier.",
    "total_income_tooltip": "Total nettoinkomst efter skatt för alla inkomsttagare.",
    "remaining_savings_tooltip": "Överskott eller underskott efter alla kostnader och skatter.",
    "show_financial_health_score_details": "Visa ekonomiskt hälsotillstånd",
    "hide_financial_health_score_details": "Dölj ekonomiskt hälsotillstånd",
    "comparing_scenarios": "Jämför {count} lånescenarion",
    "best_scenario": "Bästa scenariot",
    "worst_scenario": "Sämsta scenariot",
    "at_interest_amortization": "@ {interest} / {amortization}",
    "best_option": "Bästa alternativet",
    "worst_option": "Högsta kostnad",
    "compound_interest_cta": {
      "title": "Maximera Ditt Sparande med Ränta på Ränta",
      "description": "Du kan spara {savings} kr varje månad! Se hur mycket denna summa kan växa med ränta på ränta över tid.",
      "button": "Beräkna Ränta på Ränta"
    }
  },
  "export_import": {
    "export_csv": "Exportera CSV",
    "import_csv": "Importera CSV"
  },
  "app": {
    "title": "Budgetkollen"
  },
  "forecast": {
    "title": "Låneprognos",
    "aria": {
      "title": "Låneprognos sektion",
      "graph": "Lånebelopp över tid graf"
    },
    "tooltip": {
      "remaining_loan": "Återstående lånebelopp",
      "yearly_cost": "Årlig lånekostnad",
      "monthly_cost": "Månadsvis lånekostnad",
      "monthly_income": "Månadsinkomst",
      "monthly_savings": "Kvar att spara"
    },
    "no_loan": "Ange ett lånebelopp för att se prognosen",
    "year": "År {year}",
    "loan_payoff_in_years": "Lånet betalt om {years} år"
  },
  "not_found": {
    "title": "Sidan kunde inte hittas",
    "description": "Sidan du letar efter finns inte.",
    "back_home": "Tillbaka till startsidan"
  },
  "income": {
    "title": "Inkomster",
    "income1": "Inkomst 1 (SEK)",
    "income2": "Inkomst 2 (SEK)",
    "secondaryIncome1": "Sidoinkomst 1 (SEK)",
    "secondaryIncome2": "Sidoinkomst 2 (SEK)",
    "child_benefits": "Barnbidrag (SEK)",
    "other_benefits": "Övriga bidrag (SEK)",
    "other_incomes": "Övriga inkomster (SEK)",
    "add_extra_incomes": "Lägg till sidoinkomster",
    "title_aria": "Inkomstsektion",
    "income1_aria": "Månatlig bruttoinkomst för sökande 1 i SEK",
    "income2_aria": "Månatlig bruttoinkomst för sökande 2 i SEK",
    "secondaryIncome1_aria": "Månatlig brutto sidoinkomst för sökande 1 i SEK (utan avdrag)",
    "secondaryIncome2_aria": "Månatlig brutto sidoinkomst för sökande 2 i SEK (utan avdrag)",
    "child_benefits_aria": "Månatligt barnbidrag i SEK",
    "other_benefits_aria": "Månatliga övriga bidrag i SEK",
    "other_incomes_aria": "Månatliga övriga inkomster i SEK",
    "save": "Spara",
    "number_of_adults": "Antal vuxna i hushållet",
    "one_adult": "1 vuxen",
    "two_adults": "2 vuxna",
    "number_of_adults_full": "Välj antal vuxna i hushållet",
    "current_buffer_label": "Buffertsparande (SEK)",
    "current_buffer_aria": "Hur mycket har du på ditt buffertkonto just nu?",
    "total_monthly_income": "Total månatlig inkomst",
    "optional": "Valfritt"
  },
  "financial_health": {
    "title": "Ekonomiskt hälsotillstånd",
    "aria": {
      "title": "Ekonomiskt hälsotillstånd sektion"
    },
    "overall_score": "Totalpoäng",
    "metrics": "Nyckeltal",
    "debt_to_income": "Skuldkvot",
    "emergency_fund": "Bufferttäckning",
    "savings_rate": "Sparande",
    "housing_cost": "Boendekostnadsgrad",
    "discretionary_income": "Disponibel inkomst",
    "recommendations": "Rekommendationer",
    "recommendation_reduce_dti": "Överväg att minska dina skulder eller öka din inkomst för att förbättra din skuldkvot.",
    "recommendation_emergency_fund": "Bygg upp din buffert så att den täcker minst 3 månaders utgifter.",
    "recommendation_savings_rate": "Försök öka din sparandegrad till minst 20% av din inkomst.",
    "recommendation_housing_cost": "Dina boendekostnader är höga i förhållande till din inkomst. Fundera på sätt att minska boendekostnaderna.",
    "recommendation_discretionary_income": "Din disponibla inkomst är låg. Se över möjligheter att minska fasta utgifter.",
    "tooltips": {
      "debt_to_income": "Skuldkvot = Totala lån / Årlig bruttoinkomst (före skatt). Visar hur stor andel av din årsinkomst före skatt som skulle krävas för att betala av alla dina skulder. Lägre är bättre.",
      "emergency_fund": "Bufferttäckning = Buffert / Månadskostnader. Visar hur många månaders utgifter din buffert täcker. 300% betyder att du har tillräckligt för tre månader. Sikta på minst 300%.",
      "savings_rate": "Sparande = (Nettoinkomst - Utgifter) / Nettoinkomst. Visar hur stor andel av din inkomst du sparar varje månad.",
      "housing_cost": "Boendekostnadsgrad = Boendekostnader / Nettoinkomst. Visar hur stor andel av din inkomst som går till boende. Sikta på under 30%.",
      "discretionary_income": "Disponibel inkomst = (Nettoinkomst - Utgifter) / Nettoinkomst. Visar hur stor andel av din inkomst som är kvar efter alla utgifter.",
      "overall_score": "Totalpoängen sammanfattar din ekonomiska hälsa från 0 (svag) till 100 (utmärkt). Över 80 är starkt, 60-79 är okej, under 60 behöver förbättras. Använd rekommendationerna nedan för att förbättra din poäng."
    },
    "current_buffer_label": "Buffertsparande (SEK)",
    "current_buffer_aria": "Hur mycket har du på ditt buffertkonto just nu?"
  },
  "wizard": {
    "back": "Tillbaka",
    "next": "Nästa",
    "income": "Inkomst",
    "loans": "Lån",
    "expenses": "Utgifter",
    "summary": "Sammanfattning",
    "results": "Resultat",
    "hushallskalkylTitle": "Hushållskalkyl & Hushållsbudget",
    "hushallskalkylDesc": "Skapa din hushållsbudget och hushållskalkyl enkelt med Budgetkollen. Få full kontroll över din ekonomi och planera för framtiden.",
    "hushallskalkylCta": "Läs mer"
  },
  "summary": {
    "title": "Sammanfattning",
    "aria": {
      "title": "Sammanfattning sektion"
    },
    "incomeTitle": "Inkomster",
    "loansTitle": "Lån",
    "expensesTitle": "Utgifter",
    "income1": "Huvudinkomst 1",
    "income2": "Huvudinkomst 2",
    "secondaryIncome1": "Sidoinkomst 1",
    "secondaryIncome2": "Sidoinkomst 2",
    "childBenefits": "Barnbidrag",
    "otherBenefits": "Övriga bidrag",
    "otherIncomes": "Övriga inkomster",
    "currentBuffer": "Buffertsparande",
    "loanAmount": "Lånebelopp",
    "interestRates": "Räntesatser",
    "amortizationRates": "Amorteringssatser",
    "edit": "Redigera",
    "showAll": "Visa alla kategorier",
    "showLess": "Visa färre",
    "totalExpenses": "Totala utgifter",
    "review_before_calculating": "Granska din ekonomiska information innan du beräknar",
    "net_income": "Nettoinkomst",
    "loan_payment": "Lånebetalning",
    "per_month": "/ per månad",
    "net": "Netto",
    "adults": "vuxna",
    "adult": "vuxen",
    "estimated_monthly_surplus": "Beräknat månadsöverskott",
    "estimated_monthly_deficit": "Beräknat månadsunderskott",
    "no_loan": "Inga lån"
  },
  "hushallskalkyl": {
    "title": "Hushållskalkyl & Hushållsbudget",
    "intro": "Att skapa en hushållsbudget är ett av de smartaste stegen du kan ta för att få kontroll över din ekonomi. Med en tydlig översikt över inkomster och utgifter blir det enklare att nå dina mål – oavsett om du vill spara till en resa, bygga en buffert eller få pengarna att räcka längre varje månad. Budgetkollen finns här för att göra det enkelt att komma igång.",
    "tips_title": "Tips för en smartare budget",
    "tips": [
      "Sätt upp tydliga sparmål – både på kort och lång sikt.",
      "Gör en realistisk översikt över alla inkomster och utgifter.",
      "Prioritera buffertsparande för oförutsedda utgifter.",
      "Jämför priser och förhandla om abonnemang och försäkringar.",
      "Automatisera ditt sparande varje månad.",
      "Undvik impulsköp – vänta 24 timmar innan större inköp."
    ],
    "mistakes_title": "Vanliga misstag att undvika",
    "mistakes": [
      "Att underskatta småutgifter – de blir stora över tid.",
      "Att inte budgetera för nöjen och oförutsedda utgifter.",
      "Att glömma bort årsavgifter och sällanköp.",
      "Att inte följa upp och justera budgeten regelbundet."
    ],
    "facts_title": "Visste du att…",
    "facts": [
      "Visste du att svenskar i snitt sparar 10% av sin inkomst?",
      "En buffert på tre månadslöner rekommenderas av experter.",
      "Matkostnader är ofta hushållets näst största utgift efter boende.",
      "Att laga mat hemma kan spara över 1 000 kr/mån för en familj."
    ],
    "faq_title": "Vanliga frågor",
    "faq": [
      {
        "question": "Vad är en hushållskalkyl?",
        "answer": "En hushållskalkyl hjälper dig att få överblick över inkomster och utgifter, så att du kan planera din ekonomi smartare."
      },
      {
        "question": "Varför är en hushållsbudget viktig?",
        "answer": "Med en hushållsbudget kan du undvika oväntade utgifter och spara till dina mål."
      },
      {
        "question": "Hur ofta bör jag se över min budget?",
        "answer": "Minst en gång per kvartal, eller när din ekonomi förändras."
      },
      {
        "question": "Hur mycket bör jag spara varje månad?",
        "answer": "Sikta på minst 10% av din inkomst, men allt sparande är positivt."
      }
    ],
    "footer": "Redo att ta kontroll över din ekonomi? Prova Budgetkollen gratis och skapa din egen hushållsbudget redan idag!",
    "back_to_home": "← Tillbaka till startsidan"
  },
  "hushallsbudget": {
    "title": "Hushållsbudget - Ta Kontroll över Din Familjs Ekonomi",
    "subtitle": "Skapa din perfekta hushållsbudget med Sveriges mest använda gratis budgetverktyg. Över 50,000 svenska familjer använder redan Budgetkollen för att planera sin ekonomi.",
    "cta_button": "Starta Din Hushållsbudget Gratis",
    "meta": {
      "title": "Hushållsbudget Gratis - Skapa Din Familjebudget | Budgetkollen",
      "description": "Skapa din hushållsbudget gratis med Budgetkollen. Få full kontroll över familjebudgeten, månadsbudgeten och planera din privatekonomi smart. Sveriges bästa budgetverktyg.",
      "keywords": "hushållsbudget, familjebudget, månadsbudget, gratis budgetverktyg, privatekonomi, budgetplanering, ekonomisk planering, sparande, budgetkollen, sverige"
    },
    "features": {
      "title": "Varför Välja Budgetkollen för Din Hushållsbudget?",
      "calculator": {
        "title": "Enkel Budgetkalkylator",
        "description": "Beräkna din hushållsbudget på minuter med vår intuitiva kalkylator"
      },
      "analysis": {
        "title": "Utgiftsanalys",
        "description": "Se exakt var dina pengar går och optimera din familjebudget"
      },
      "planning": {
        "title": "Sparplanering",
        "description": "Planera ditt sparande och se hur dina mål utvecklas över tid"
      },
      "goals": {
        "title": "Ekonomiska Mål",
        "description": "Sätt upp och följ dina finansiella mål med precision"
      }
    },
    "guide": {
      "title": "Så Skapar Du Din Perfekta Hushållsbudget",
      "step1": {
        "title": "Samla Alla Inkomster",
        "description": "Lista alla månadsinkomster för familjen inklusive löner, barnbidrag och andra inkomster."
      },
      "step2": {
        "title": "Kartlägg Alla Utgifter",
        "description": "Gå igenom alla dina utgifter från boende och mat till fritid och sparande."
      },
      "step3": {
        "title": "Analysera och Optimera",
        "description": "Använd våra verktyg för att se var du kan spara pengar och förbättra din ekonomi."
      },
      "step4": {
        "title": "Följ Upp Regelbundet",
        "description": "Uppdatera din hushållsbudget månadsvis för att hålla den aktuell och relevant."
      }
    },
    "tips": {
      "title": "Expertråd för Din Hushållsbudget",
      "working_tips": {
        "title": "Budgettips som Fungerar",
        "tip1": "Använd 50/30/20-regeln för balanserad budget",
        "tip2": "Sätt upp automatiska sparanden",
        "tip3": "Granska abonnemang och prenumerationer",
        "tip4": "Planera för oförutsedda utgifter"
      },
      "mistakes": {
        "title": "Vanliga Budgetfel att Undvika",
        "mistake1": "Glömma bort årsutgifter som försäkringar",
        "mistake2": "Sätta orealistiska sparmål",
        "mistake3": "Inte ha buffert för nöjen",
        "mistake4": "Inte följa upp budgeten regelbundet"
      }
    },
    "faq": {
      "title": "Vanliga Frågor om Hushållsbudget",
      "q1": {
        "question": "Vad är en hushållsbudget?",
        "answer": "En hushållsbudget är en plan över hur familjen ska använda sina pengar varje månad. Den inkluderar alla inkomster och utgifter för att ge en komplett bild av familjens ekonomi."
      },
      "q2": {
        "question": "Hur mycket ska jag spara varje månad?",
        "answer": "Experter rekommenderar att spara minst 20% av din månadsinkomst. Men börja med det du kan - även 5-10% är bra för att komma igång med sparandet."
      },
      "q3": {
        "question": "Vad är skillnaden mellan familjebudget och hushållsbudget?",
        "answer": "Termerna används ofta synonymt. En hushållsbudget inkluderar alla som bor i hemmet, medan familjebudget fokuserar på kärnfamiljen. Båda hjälper dig att planera din ekonomi."
      },
      "q4": {
        "question": "Hur ofta bör jag uppdatera min hushållsbudget?",
        "answer": "Uppdatera din hushållsbudget månadsvis för bästa resultat. Gör större förändringar kvartalsvis eller när din ekonomiska situation förändras betydligt."
      }
    },
    "cta": {
      "title": "Börja Skapa Din Hushållsbudget Idag",
      "subtitle": "Gå med i över 50,000 svenska familjer som redan använder Budgetkollen",
      "button": "Kom Igång Gratis Nu"
    }
  },
  "compound_interest": {
    "title": "Ränta på Ränta Kalkylator - Månadssparande & Långsiktigt Sparande",
    "subtitle": "Beräkna ränta på ränta för ditt månadssparande. Se hur regelbundet sparande i fonder och aktier kan bygga betydande förmögenhet över tid genom sammansatt avkastning.",
    "meta": {
      "title": "Ränta-på-Ränta Kalkylator Gratis - Se Din Investering Växa | Budgetkollen",
      "description": "Beräkna ränta-på-ränta och se hur dina investeringar växer över tid. Gratis ränta-på-ränta kalkylator med visuella diagram. Perfekt för långsiktig ekonomisk planering i Sverige.",
      "keywords": "ränta på ränta kalkylator, investeringskalkylator, sparkalkylator, ekonomisk planering, långsiktigt sparande, förmögenhetsbyggande, investeringstillväxt, budgetkollen"
    },
    "intro": {
      "title": "Magin med Ränta på Ränta och Månadssparande",
      "description": "Ränta på ränta kallas ofta världens åttonde underverk. När du kombinerar månadssparande med ränta på ränta tjänar du avkastning inte bara på din ursprungliga investering, utan även på all avkastning du har samlat över tid. Detta skapar en snöbollseffekt som dramatiskt kan öka din förmögenhet på lång sikt.",
      "einstein_quote": "Ränta-på-ränta är världens åttonde underverk. Den som förstår den, tjänar på den; den som inte gör det, betalar för den.",
      "einstein_attribution": "Ofta tillskrivet Albert Einstein",
      "why_important": "Nyckeln till att maximera ränta på ränta är tid och konsistens. Genom månadssparande i aktiefonder, indexfonder eller ETF:er, även med små belopp, kan du bygga upp betydande förmögenhet. Den här kalkylatorn hjälper dig att visualisera exakt hur ditt månadssparande kan växa genom kraften i ränta på ränta.",
      "connection_to_budget": "Efter att ha skapat din hushållsbudget med Budgetkollen kan du använda denna ränta på ränta kalkylator för att se hur ditt månadssparande kan växa. Perfekt för pensionssparande, barnsparande eller andra långsiktiga sparmål."
    },
    "calculator": {
      "title": "Beräkna Ränta på Ränta & Månadssparande",
      "description": "Justera värdena nedan för att se hur ditt månadssparande kan växa med ränta på ränta över tid"
    },
    "inputs": {
      "start_sum_label": "Startbelopp (SEK)",
      "start_sum_description": "Det initiala beloppet du har att investera",
      "monthly_savings_label": "Månatligt Sparande (SEK)",
      "monthly_savings_description": "Hur mycket du planerar att spara och investera varje månad",
      "yearly_return_label": "Förväntad Årlig Avkastning (%)",
      "yearly_return_description": "Den genomsnittliga årliga avkastningen du förväntar dig på dina investeringar",
      "investment_horizon_label": "Investeringsperiod (År)",
      "investment_horizon_description": "Hur länge du planerar att hålla dina pengar investerade"
    },
    "results": {
      "title": "Din Investeringstillväxt",
      "description": "Här är hur dina pengar kan växa över {years} år",
      "total_value": "Total Portföljvärde",
      "start_sum": "Initial Investering",
      "total_savings": "Totalt Sparat Tillagt",
      "compound_returns": "Investeringstillväxt",
      "growth_summary": "Börjar med {startSum} och sparar {totalSavings} över {years} år, kan dina investeringar växa med {returns} för att nå ett totalt värde på {total}."
    },
    "chart": {
      "title": "Investeringstillväxt Över Tid",
      "description": "Se hur din portfölj växer genom sparande och sammansatt avkastning",
      "aria_title": "Investeringstillväxt visualisering som visar fördelningen av portföljvärde över tid"
    },
    "legend": {
      "start_sum": "Initial Investering",
      "accumulated_savings": "Månatligt Sparande",
      "compound_returns": "Investeringsavkastning"
    },
    "tooltip": {
      "year": "År {year}",
      "start_sum": "Initial Investering",
      "accumulated_savings": "Totalt Sparat Tillagt",
      "compound_returns": "Investeringstillväxt",
      "total_value": "Total Portföljvärde"
    },
    "tips": {
      "title": "Smarta Investeringstips",
      "tip1": "Börja investera så tidigt som möjligt - tid är din största tillgång",
      "tip2": "Investera regelbundet och konsekvent, oavsett marknadsförhållanden",
      "tip3": "Diversifiera dina investeringar för att minska risken",
      "tip4": "Håll dina investeringskostnader låga för att maximera avkastningen",
      "tip5": "Håll dig investerad på lång sikt - panikera inte under marknadsnedgångar",
      "tip6": "Återinvestera all utdelning och avkastning för att maximera sammansättningen"
    },
    "disclaimer": {
      "title": "Viktig Ansvarsfriskrivning",
      "text": "Denna kalkylator ger uppskattningar baserade på de indata du anger. Faktisk investeringsavkastning kan variera betydligt och tidigare resultat garanterar inte framtida resultat. Rådfråga alltid en finansiell rådgivare innan du fattar investeringsbeslut."
    },
    "cta": {
      "title": "Redo att Börja Bygga Förmögenhet?",
      "subtitle": "Använd vår hushållsbudget kalkylator för att hitta pengar du kan investera varje månad",
      "button": "Skapa Din Budget"
    }
  }
};
export default messages;