// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "loan_parameters": {
    "title": "Låneparametrar",
    "add_loans": "Lägg till lån",
    "hide_loans": "Dölj lån",
    "loan_amount": "Lånebelopp (SEK)",
    "interest_rates": "Räntesatser (%)",
    "amortization_rates": "Amorteringssatser (%)",
    "title_aria": "Avsnitt för låneparametrar",
    "loan_amount_aria": "Lånebelopp i SEK",
    "interest_rates_aria": "Välj en eller flera räntesatser",
    "amortization_rates_aria": "Välj en eller flera amorteringssatser"
  },
  "expense_categories": {
    "title": "Utgiftskategorier",
    "add_expenses": "Lägg till utgifter",
    "hide_expenses": "Dölj utgifter",
    "total_expenses": "Totala utgifter",
    "home": {
      "name": "Hem",
      "electricity-heating": "El och uppvärmning",
      "pets": "Husdjur",
      "streaming-internet-phone": "Streaming, internet och telefon",
      "house-cleaning": "Städning",
      "rent-monthly-fee": "Hyra och avgift",
      "interior-decoration": "Inredning och möbler",
      "mortgage": "Bolån",
      "home-improvements": "Renovering och förbättringar",
      "holiday-home": "Fritidshus",
      "water-garbage": "Vatten och sophämtning",
      "gardening": "Trädgård",
      "home-alarm": "Larm",
      "other-household": "Övriga hushållstjänster"
    },
    "car-transportation": {
      "name": "Bil och transport",
      "charging": "Laddning",
      "parking": "Parkering",
      "fuel": "Bränsle",
      "car-service": "Bilservice",
      "taxi": "Taxi",
      "public-transportation": "Kollektivtrafik",
      "car-cleaning": "Biltvätt",
      "car-loan-lease": "Billån och leasing",
      "motorcycle": "Motorcykel",
      "other-transportation": "Övriga transporter"
    },
    "leisure": {
      "name": "Fritid",
      "association-memberships": "Föreningsmedlemskap",
      "golfing": "Golf",
      "hunting": "Jakt",
      "hiking-outdoor": "Vandring och friluftsliv",
      "arts-crafts": "Konst och hantverk",
      "dancing": "Dans",
      "skiing-winter": "Skidåkning och vintersport",
      "horseback-riding": "Ridning",
      "biking": "Cykling",
      "photographing": "Fotografering",
      "music-instruments": "Musik och instrument",
      "parties-celebrations": "Fester och firanden",
      "charities": "Välgörenhet",
      "movies-events": "Bio, teater och evenemang",
      "lotteries-betting": "Lotterier och spel",
      "bars-nightclubs": "Barer, pubar och nattklubbar"
    },
    "shopping-services": {
      "name": "Shopping och tjänster",
      "flowers-decor": "Blommor och dekoration",
      "electronics": "Hemelektronik",
      "books-games": "Böcker och spel",
      "music-apps": "Musik och appar",
      "subscriptions-media": "Prenumerationer och media",
      "clothes-shoes": "Kläder och skor",
      "dry-clean-tailor": "Kemtvätt och skräddare",
      "jewelry-accessories": "Smycken och accessoarer",
      "tobacco": "Tobak",
      "alcohol": "Alkohol",
      "gifts": "Presenter",
      "shopping-other": "Shopping och tjänster, övrigt"
    },
    "loans-tax-fees": {
      "name": "Lån, skatt och avgifter",
      "late-fees": "Förseningsavgifter",
      "bank-fees": "Bank- och serviceavgifter",
      "private-loans": "Privatlån",
      "tax-payments": "Skattebetalningar",
      "other-loans-fees": "Övriga lån, skatter och avgifter"
    },
    "health-beauty": {
      "name": "Hälsa och skönhet",
      "pharmacy": "Apotek",
      "healthcare": "Sjukvård",
      "sports-exercise": "Sport och träning",
      "spa-massage": "Spa och massage",
      "beauty-products": "Skönhetsprodukter",
      "hairdresser": "Frisör",
      "optician": "Optiker",
      "other-health-beauty": "Övrig hälsa och skönhet"
    },
    "children": {
      "name": "Barn",
      "babysitting": "Barnpassning",
      "children-clothing": "Barnkläder",
      "children-toys": "Barnleksaker",
      "allowance": "Vecko- och månadspeng",
      "children-activities": "Barnaktiviteter",
      "childcare-products": "Barnomsorgsprodukter",
      "alimony": "Underhåll",
      "preschool-after-school": "Förskola och fritids",
      "children-other": "Barn, övrigt"
    },
    "uncategorized": {
      "name": "Okategoriserade utgifter",
      "cash-withdrawals": "Kontantuttag",
      "swish": "Swish",
      "uncategorized-transfers": "Okategoriserade överföringar",
      "uncategorized-other": "Okategoriserade utgifter, övrigt",
      "uncategorized-credit-card": "Okategoriserade kortköp"
    },
    "insurance": {
      "name": "Försäkring",
      "household-insurance": "Hemförsäkring",
      "car-insurance": "Bilförsäkring",
      "life-health-insurance": "Liv- och sjukförsäkring",
      "income-insurance": "A-kassa och/eller inkomstförsäkring",
      "accident-insurance": "Olycksfallsförsäkring",
      "insurance-other": "Övriga försäkringar"
    },
    "savings-investments": {
      "name": "Sparande och investeringar",
      "savings-buffer": "Buffertsparande",
      "pension-savings": "Pensionssparande",
      "securities-funds": "Värdepapper och fonder",
      "savings-children": "Barnsparande",
      "savings-other": "Sparande, övrigt"
    },
    "vacation-traveling": {
      "name": "Semester och resor",
      "vacation-transport": "Transport på semester",
      "hotels-accommodation": "Hotell och boende",
      "vacation-entertainment": "Nöjen på semester",
      "vacation-food": "Mat och levnadskostnader på semester",
      "vacation-other": "Semester och resor, övrigt"
    },
    "education": {
      "name": "Utbildning",
      "student-loan": "Studielån",
      "education-fees": "Utbildningsavgifter",
      "educational-equipment": "Utbildningsmaterial",
      "education-other": "Utbildning, övrigt"
    },
    "food": {
      "name": "Mat",
      "groceries": "Livsmedel",
      "fast-food": "Snabbmat",
      "candy-kiosks": "Godis, glass och kiosker",
      "restaurants-cafes": "Restauranger och caféer",
      "food-other": "Mat, övrigt"
    },
    "aria": {
      "title": "Utgiftskategorier sektion",
      "category": "Utgiftskategori: {{category}}",
      "subcategory_input": "Inmatning för {{subcategory}} i {{category}}"
    }
  },
  "expense_breakdown": {
    "title": "Utgiftsfördelning",
    "aria": {
      "title": "Utgiftsfördelning sektion"
    },
    "no_expenses": "Inga utgifter att visa"
  },
  "results": {
    "title": "Beräkningsresultat",
    "aria": {
      "title": "Beräkningsresultat sektion"
    },
    "interest_rate": "Ränta",
    "amortization": "Amortering",
    "housing_cost": "Boendekostnad",
    "total_expenses": "Totala utgifter",
    "total_income": "Total inkomst",
    "remaining_savings": "Kvar att spara",
    "interest_rate_tooltip": "Räntesatsen som används för låneberäkningen.",
    "amortization_tooltip": "Amorteringssatsen som används för låneberäkningen.",
    "housing_cost_tooltip": "Summa av amorteringar, räntebetalningar, hyra/månadsavgift, el/värme, bolån och vatten/sopor.",
    "total_expenses_tooltip": "Alla månatliga utgifter, inklusive boende och övriga kategorier.",
    "total_income_tooltip": "Total nettoinkomst efter skatt för alla inkomsttagare.",
    "remaining_savings_tooltip": "Överskott eller underskott efter alla kostnader och skatter.",
    "financial_health_score_details": "Visa ekonomiskt hälsotillstånd"
  },
  "export_import": {
    "export_csv": "Exportera CSV",
    "import_csv": "Importera CSV"
  },
  "app": {
    "title": "Budgetkollen"
  },
  "forecast": {
    "title": "Låneprognos",
    "aria": {
      "title": "Låneprognos sektion",
      "graph": "Lånebelopp över tid graf"
    },
    "tooltip": {
      "remaining_loan": "Återstående lånebelopp",
      "yearly_cost": "Årlig lånekostnad",
      "monthly_cost": "Månadsvis lånekostnad",
      "monthly_income": "Månadsinkomst",
      "monthly_savings": "Kvar att spara"
    },
    "no_loan": "Ange ett lånebelopp för att se prognosen",
    "year": "År {year}"
  },
  "not_found": {
    "title": "Sidan kunde inte hittas",
    "description": "Sidan du letar efter finns inte.",
    "back_home": "Tillbaka till startsidan"
  },
  "income": {
    "title": "Inkomster",
    "income1": "Inkomst 1 (SEK)",
    "income2": "Inkomst 2 (SEK)",
    "secondaryIncome1": "Sidoinkomst 1 (SEK)",
    "secondaryIncome2": "Sidoinkomst 2 (SEK)",
    "child_benefits": "Barnbidrag (SEK)",
    "other_benefits": "Övriga bidrag (SEK)",
    "other_incomes": "Övriga inkomster (SEK)",
    "add_extra_incomes": "Lägg till sidoinkomster",
    "title_aria": "Inkomstsektion",
    "income1_aria": "Månatlig bruttoinkomst för sökande 1 i SEK",
    "income2_aria": "Månatlig bruttoinkomst för sökande 2 i SEK",
    "secondaryIncome1_aria": "Månatlig brutto sidoinkomst för sökande 1 i SEK (utan avdrag)",
    "secondaryIncome2_aria": "Månatlig brutto sidoinkomst för sökande 2 i SEK (utan avdrag)",
    "child_benefits_aria": "Månatligt barnbidrag i SEK",
    "other_benefits_aria": "Månatliga övriga bidrag i SEK",
    "other_incomes_aria": "Månatliga övriga inkomster i SEK",
    "save": "Spara",
    "number_of_adults": "Antal vuxna i hushållet",
    "one_adult": "1 vuxen",
    "two_adults": "2 vuxna",
    "number_of_adults_full": "Välj antal vuxna i hushållet",
    "current_buffer_label": "Buffertsparande (SEK)",
    "current_buffer_aria": "Hur mycket har du på ditt buffertkonto just nu?"
  },
  "financial_health": {
    "title": "Ekonomiskt hälsotillstånd",
    "aria": {
      "title": "Ekonomiskt hälsotillstånd sektion"
    },
    "overall_score": "Totalpoäng",
    "metrics": "Nyckeltal",
    "debt_to_income": "Skuldkvot",
    "emergency_fund": "Bufferttäckning",
    "savings_rate": "Sparande",
    "housing_cost": "Boendekostnadsgrad",
    "discretionary_income": "Disponibel inkomst",
    "recommendations": "Rekommendationer",
    "recommendation_reduce_dti": "Överväg att minska dina skulder eller öka din inkomst för att förbättra din skuldkvot.",
    "recommendation_emergency_fund": "Bygg upp din buffert så att den täcker minst 3 månaders utgifter.",
    "recommendation_savings_rate": "Försök öka din sparandegrad till minst 20% av din inkomst.",
    "recommendation_housing_cost": "Dina boendekostnader är höga i förhållande till din inkomst. Fundera på sätt att minska boendekostnaderna.",
    "recommendation_discretionary_income": "Din disponibla inkomst är låg. Se över möjligheter att minska fasta utgifter.",
    "tooltips": {
      "debt_to_income": "Skuldkvot = Totala lån / Årlig bruttoinkomst (före skatt). Visar hur stor andel av din årsinkomst före skatt som skulle krävas för att betala av alla dina skulder. Lägre är bättre.",
      "emergency_fund": "Bufferttäckning = Buffert / Månadskostnader. Visar hur många månaders utgifter din buffert täcker. 300% betyder att du har tillräckligt för tre månader. Sikta på minst 300%.",
      "savings_rate": "Sparande = (Nettoinkomst - Utgifter) / Nettoinkomst. Visar hur stor andel av din inkomst du sparar varje månad.",
      "housing_cost": "Boendekostnadsgrad = Boendekostnader / Nettoinkomst. Visar hur stor andel av din inkomst som går till boende. Sikta på under 30%.",
      "discretionary_income": "Disponibel inkomst = (Nettoinkomst - Utgifter) / Nettoinkomst. Visar hur stor andel av din inkomst som är kvar efter alla utgifter.",
      "overall_score": "Totalpoängen sammanfattar din ekonomiska hälsa från 0 (svag) till 100 (utmärkt). Över 80 är starkt, 60-79 är okej, under 60 behöver förbättras. Använd rekommendationerna nedan för att förbättra din poäng."
    },
    "current_buffer_label": "Buffertsparande (SEK)",
    "current_buffer_aria": "Hur mycket har du på ditt buffertkonto just nu?"
  }
};
export default messages;